version: '3.0'

services:
  database:
    image: postgres
    container_name: "todowebflux-db"
    environment:
      - POSTGRES_DB=todowebflux
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - webflux_data:/var/lib/postgresql/data

volumes:
  webflux_data: