CREATE SEQUENCE IF NOT EXISTS tb_todo_id_seq;

CREATE TABLE IF NOT EXISTS TB_TODO (
  ID INTEGER PRIMARY KEY NOT NULL DEFAULT NEXTVAL('tb_todo_id_seq'),
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(1000) NOT NULL,
  CREATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp,
  UPDATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp
);